# file: roles/jboss-eap/install/tasks/main.yml

- name: create JBoss EAP Installation Directory
  file: path={{ eap_install_dir }} owner=root group=root state=directory

- name: install unzip
  yum: name=unzip state=present

- name: unarchive JBoss EAP Binary File
  unarchive: src={{ eap_archive }} dest={{ eap_install_dir }}

- name: remove JBoss EAP Home Directory, if exists
  file: path={{ eap_home_dir }} state=absent

- name: rename JBoss EAP Home Directory
  command: mv chdir={{ eap_install_dir }} {{ eap_extracted_dir }} {{ eap_version }}

- name: chown {{ eap_home_dir }}
  file: path={{ eap_home_dir }} owner={{ eap_user }} group={{ eap_group }} recurse=yes
